import os
import pandas as pd
import yfinance as yf


UNIVERSE_FILE = "universe.py"

NIFTY500_URL = (
    "https://www.niftyindices.com/IndexConstituent/"
    "ind_nifty500list.csv"
)

WIKIPEDIA_URL = "https://en.wikipedia.org/wiki/NIFTY_500"


# =========================================================
# DYNAMIC NIFTY 500 UNIVERSE
# =========================================================

def get_nifty500_symbols():
    """
    Fetch the CURRENT Nifty 500 constituents.

    Priority:
        1. Official Nifty Indices CSV
        2. Wikipedia fallback

    Returns:
        List of Yahoo Finance symbols ending in .NS
    """

    print()
    print("=" * 64)
    print("UPDATING NIFTY 500 UNIVERSE")
    print("=" * 64)

    # -----------------------------------------------------
    # Method 1 — Official Nifty 500 CSV
    # -----------------------------------------------------

    try:

        print("Source : Official Nifty Indices")

        df = pd.read_csv(
            NIFTY500_URL,
            storage_options={
                "User-Agent": "Mozilla/5.0"
            }
        )

        symbol_column = None

        for column in ["Symbol", "SYMBOL", "symbol"]:

            if column in df.columns:

                symbol_column = column

                break

        if symbol_column is None:

            raise ValueError(
                "Could not find Symbol column."
            )

        symbols = (
            df[symbol_column]
            .dropna()
            .astype(str)
            .str.strip()
            .str.upper()
            .tolist()
        )

        symbols = [
            symbol if symbol.endswith(".NS")
            else symbol + ".NS"
            for symbol in symbols
            if symbol
        ]

        symbols = sorted(set(symbols))

        if len(symbols) >= 400:

            print(
                f"Current Nifty 500 constituents : "
                f"{len(symbols)}"
            )

            return symbols

    except Exception as e:

        print(
            "Official Nifty 500 download failed:"
        )

        print(f"Reason: {e}")

    # -----------------------------------------------------
    # Method 2 — Wikipedia fallback
    # -----------------------------------------------------

    try:

        print()
        print("Trying Wikipedia fallback...")

        tables = pd.read_html(
            WIKIPEDIA_URL
        )

        for table in tables:

            for column in table.columns:

                values = (
                    table[column]
                    .dropna()
                    .astype(str)
                    .str.strip()
                )

                candidate_count = sum(
                    values.str.match(
                        r"^[A-Za-z0-9&._-]+$"
                    )
                )

                if candidate_count < 400:

                    continue

                symbols = [
                    value.upper()
                    for value in values
                    if (
                        len(value) <= 30
                        and value.lower()
                        not in {
                            "symbol",
                            "company name"
                        }
                    )
                ]

                symbols = [
                    symbol if symbol.endswith(".NS")
                    else symbol + ".NS"
                    for symbol in symbols
                ]

                symbols = sorted(set(symbols))

                if len(symbols) >= 400:

                    print(
                        f"Current Nifty 500 constituents : "
                        f"{len(symbols)}"
                    )

                    return symbols

    except Exception as e:

        print(
            "Wikipedia fallback failed:"
        )

        print(f"Reason: {e}")

    raise RuntimeError(
        "Could not obtain current Nifty 500 universe."
    )


# =========================================================
# WRITE universe.py
# =========================================================

def update_universe_file(symbols):
    """
    Write the latest Nifty 500 symbols into universe.py.
    """

    content = '''"""
TRADELENS — DYNAMIC NIFTY 500 UNIVERSE

This file is automatically generated by trade_data.py.

DO NOT EDIT MANUALLY.

The symbols represent the latest available
Nifty 500 constituents at the time of refresh.
"""

symbols = [
'''

    for symbol in symbols:

        content += (
            f'    "{symbol}",\n'
        )

    content += ''']
'''

    with open(
        UNIVERSE_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(content)

    print()
    print(
        f"Updated : {UNIVERSE_FILE}"
    )

    print(
        f"Symbols : {len(symbols)}"
    )


# =========================================================
# PUBLIC FUNCTION
# =========================================================

def refresh_nifty500_universe():
    """
    Download the current Nifty 500 membership
    and regenerate universe.py.
    """

    symbols = get_nifty500_symbols()

    update_universe_file(symbols)

    return symbols


# =========================================================
# CURRENT / LIVE MARKET DATA
# =========================================================

def get_market_data(symbol):
    """
    Download 1 year of daily market data.
    """

    data = yf.download(
        symbol,
        period="1y",
        interval="1d",
        auto_adjust=False,
        progress=False
    )

    return data


# =========================================================
# DETERMINE ANALYSIS DATE
# =========================================================

def get_latest_trading_date(data):
    """
    Determine the latest valid trading date available
    in the downloaded Yahoo Finance data.

    The analysis date is NOT today's calendar date.

    It is the latest date for which market data actually
    exists in the downloaded dataset.

    Example:

        Today       : Saturday, 29-Aug-2026
        Latest data : Friday, 28-Aug-2026

        Analysis Date = 28-Aug-2026
    """

    if data is None or data.empty:

        raise RuntimeError(
            "Market data is empty. "
            "Cannot determine analysis date."
        )

    # -----------------------------------------------------
    # The index contains the trading dates.
    # -----------------------------------------------------

    valid_dates = pd.DatetimeIndex(
        data.index
    ).dropna()

    if len(valid_dates) == 0:

        raise RuntimeError(
            "No valid trading dates found "
            "in market data."
        )

    # -----------------------------------------------------
    # Latest date actually returned by Yahoo.
    # -----------------------------------------------------

    latest_date = valid_dates.max()

    return latest_date


# =========================================================
# MULTI-YEAR HISTORICAL DATA
# =========================================================

def get_historical_market_data_for_symbols(
    symbols,
    period="5y"
):
    """
    Download multi-year OHLCV data for backtesting.
    """

    data = yf.download(
        symbols,
        period=period,
        interval="1d",
        auto_adjust=False,
        progress=True,
        group_by="column",
        threads=True
    )

    valid_symbols = []
    invalid_symbols = []

    for symbol in symbols:

        try:

            close_prices = (
                data["Close"][symbol]
            )

            if close_prices.dropna().empty:

                invalid_symbols.append(symbol)

            else:

                valid_symbols.append(symbol)

        except (KeyError, TypeError):

            invalid_symbols.append(symbol)

    print()
    print(
        "Historical data period:",
        period
    )

    print(
        "Requested symbols:",
        len(symbols)
    )

    print(
        "Valid symbols:",
        len(valid_symbols)
    )

    print(
        "Invalid symbols:",
        len(invalid_symbols)
    )

    return data, valid_symbols


# =========================================================
# CURRENT MARKET DATA FOR ALL SYMBOLS
# =========================================================

def get_market_data_for_symbols(symbols):
    """
    Download 1 year of daily OHLCV data.

    Returns:

        data
        valid_symbols
        analysis_date

    analysis_date is the latest trading date actually
    available in the downloaded Yahoo Finance dataset.
    """

    data = yf.download(
        symbols,
        period="1y",
        interval="1d",
        auto_adjust=False,
        progress=True,
        group_by="column",
        threads=True
    )

    # -----------------------------------------------------
    # Validate data
    # -----------------------------------------------------

    if data is None or data.empty:

        raise RuntimeError(
            "Yahoo Finance returned no market data."
        )

    # -----------------------------------------------------
    # Determine latest available trading date
    # -----------------------------------------------------

    analysis_date = get_latest_trading_date(
        data
    )

    # -----------------------------------------------------
    # Validate symbols
    # -----------------------------------------------------

    valid_symbols = []
    invalid_symbols = []

    for symbol in symbols:

        try:

            close_prices = (
                data["Close"][symbol]
            )

            if close_prices.dropna().empty:

                invalid_symbols.append(symbol)

            else:

                valid_symbols.append(symbol)

        except (KeyError, TypeError):

            invalid_symbols.append(symbol)

    # -----------------------------------------------------
    # Print download information
    # -----------------------------------------------------

    print()

    print(
        "Requested symbols:",
        len(symbols)
    )

    print(
        "Valid symbols:",
        len(valid_symbols)
    )

    print(
        "Invalid symbols:",
        len(invalid_symbols)
    )

    print()

    print(
        "Latest available trading date:",
        analysis_date.strftime("%d-%b-%Y")
    )

    print(
        "Analysis date:",
        analysis_date.strftime("%d-%b-%Y")
    )

    return (
        data,
        valid_symbols,
        analysis_date
    )
