from __future__ import annotations

import json
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any


# =============================================================================
# SMALLCAPSIPLAB - PRODUCTION MAIN ENTRY POINT
# =============================================================================
#
# IMPORTANT:
#
#   main.py DOES NOT run backtest.py.
#
#   main.py is a PRODUCTION/READ-ONLY reporting and SIP-decision layer.
#
#   It reads the already-generated files from:
#
#       C:\Users\natte\Documents\Project\InvestmentResearchLab\
#       src\SmallCapSIPLab\results
#
#   The expensive historical research process is performed ONLY by:
#
#       python backtest.py
#
#   Run backtest.py separately whenever historical research/data needs
#   to be refreshed.
#
#
# PRODUCTION SIP RULE
# -------------------
#
#   Monthly SIP                  : ₹10,000
#   New SIP allocation            : 100% to Rank #1
#   Informational ranks           : #2 to #5
#   Existing holdings             : Remain invested
#   Automatic selling             : NO
#   Automatic rebalancing         : NO
#   Ranking frequency              : Monthly
#
#
# STRATEGY SELECTION
# ------------------
#
#   The strategy is NOT hardcoded.
#
#   main.py reads the latest completed backtest summary and checks:
#
#       1. Highest historical XIRR
#       2. Highest historical risk-adjusted composite
#
#   If both identify the same strategy:
#
#       That strategy becomes the current live-style strategy.
#
#   If they disagree:
#
#       No strategy is silently selected.
#       No SIP instruction is issued.
#
#
# HISTORICAL BACKTEST
# -------------------
#
#   Latest supplied run:
#
#       Period       : 2014-01-01 -> 2026-09-30
#       SIP          : ₹10,000/month
#       Portfolio    : Rank #1 only
#       Contributions: ₹11,60,000
#       Completed SIPs: 116
#
#   TREND:
#
#       XIRR                    : 20.10%
#       TWR                     : 433.68%
#       Volatility              : 20.44%
#       Maximum Drawdown        : -29.06%
#       Sharpe                  : 0.967
#       Sortino                 : 0.889
#       Calmar                  : 0.692
#       Risk-adjusted composite : 0.78
#       Final value              : ₹32,18,008
#
#
# IMPORTANT
# ---------
#
#   The values above are documentation only.
#
#   main.py does NOT recalculate them.
#
#   It reads the latest saved result files generated by backtest.py.
#
#
# RUN
# ---
#
#   python main.py
#
# From:
#
#   C:\Users\natte\Documents\Project\InvestmentResearchLab\src\SmallCapSIPLab
#
# =============================================================================


# =============================================================================
# PATH SETUP
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent

RESULTS_DIR = (
    BASE_DIR
    / "results"
)

SUMMARY_FILE = (
    RESULTS_DIR
    / "summary.json"
)

STRATEGY_METRICS_FILE = (
    RESULTS_DIR
    / "strategy_metrics.csv"
)


# =============================================================================
# PRODUCTION CONSTANTS
# =============================================================================

LIVE_SIP_AMOUNT = 10_000.0

LIVE_PORTFOLIO_SIZE = 1

DISPLAY_RANKS = 5

STRATEGY_CANDIDATES = [
    "MOMENTUM",
    "TREND",
    "QUALITY_MOMENTUM",
    "RISK_ADJUSTED",
    "DRAWDOWN_RECOVERY",
    "CONSISTENCY",
]

# A production result should not silently become ancient.
#
# This does NOT trigger a backtest.
#
# If the saved research is older than this, main.py stops the SIP action
# and asks the user to refresh backtest.py manually.
MAX_RESULT_AGE_DAYS = 45


# =============================================================================
# HELPERS
# =============================================================================

def safe_float(
    value: Any,
) -> float | None:

    try:

        number = float(value)

        if number != number:
            return None

        return number

    except (
        TypeError,
        ValueError,
    ):

        return None


def safe_int(
    value: Any,
) -> int | None:

    try:

        number = float(value)

        if number != number:
            return None

        return int(number)

    except (
        TypeError,
        ValueError,
    ):

        return None


def format_pct(
    value: Any,
    decimals: int = 2,
) -> str:

    number = safe_float(value)

    if number is None:

        return "N/A"

    return f"{number * 100:.{decimals}f}%"


def format_money(
    value: Any,
) -> str:

    number = safe_float(value)

    if number is None:

        return "N/A"

    return f"₹{number:,.0f}"


def format_nav(
    value: Any,
) -> str:

    number = safe_float(value)

    if number is None:

        return "N/A"

    return f"₹{number:,.4f}"


def format_number(
    value: Any,
    decimals: int = 3,
) -> str:

    number = safe_float(value)

    if number is None:

        return "N/A"

    return f"{number:.{decimals}f}"


def format_datetime(
    value: Any,
) -> str:

    if value is None:

        return "N/A"

    text = str(value).strip()

    if not text:

        return "N/A"

    try:

        dt = datetime.fromisoformat(
            text.replace(
                "Z",
                "+00:00",
            )
        )

        return dt.strftime(
            "%Y-%m-%d %H:%M:%S"
        )

    except ValueError:

        return text


def get_file_modified_time(
    filename: Path,
) -> datetime | None:

    try:

        return datetime.fromtimestamp(
            filename.stat().st_mtime
        )

    except OSError:

        return None


def days_since(
    dt: datetime | None,
) -> float | None:

    if dt is None:

        return None

    return (
        datetime.now()
        - dt
    ).total_seconds() / 86400.0


# =============================================================================
# HEADER
# =============================================================================

def print_header() -> None:

    print()

    print("=" * 100)
    print("SMALLCAPSIPLAB")
    print("SMALL-CAP MUTUAL FUND SIP RESEARCH")
    print("=" * 100)

    print()

    print(
        f"Project directory       : "
        f"{BASE_DIR}"
    )

    print(
        f"Results directory       : "
        f"{RESULTS_DIR}"
    )

    print()

    print(
        "MODE                    : "
        "PRODUCTION / READ-ONLY"
    )

    print(
        "Historical backtest     : "
        "NOT RUN BY main.py"
    )

    print(
        "MFAPI download          : "
        "NOT RUN BY main.py"
    )

    print(
        "NAV download            : "
        "NOT RUN BY main.py"
    )

    print()

    print("PRODUCTION SIP MODEL")
    print("-" * 100)

    print(
        f"Monthly SIP             : "
        f"{format_money(LIVE_SIP_AMOUNT)}"
    )

    print(
        "New SIP allocation      : "
        "100% to Rank #1"
    )

    print(
        "Informational ranks     : "
        f"Top {DISPLAY_RANKS}"
    )

    print(
        "Existing holdings       : "
        "Remain invested"
    )

    print(
        "Automatic selling       : "
        "NO"
    )

    print(
        "Automatic rebalancing   : "
        "NO"
    )

    print(
        "Re-evaluation            : "
        "Monthly"
    )

    print()


# =============================================================================
# RESULTS VALIDATION
# =============================================================================

def validate_result_files() -> None:

    print("=" * 100)
    print("RESULT VALIDATION")
    print("=" * 100)

    print()

    if not RESULTS_DIR.exists():

        raise RuntimeError(
            "Results directory does not exist:\n"
            f"{RESULTS_DIR}\n\n"
            "Run backtest.py first."
        )

    if not SUMMARY_FILE.exists():

        raise RuntimeError(
            "summary.json was not found:\n"
            f"{SUMMARY_FILE}\n\n"
            "Run backtest.py first."
        )

    if not STRATEGY_METRICS_FILE.exists():

        raise RuntimeError(
            "strategy_metrics.csv was not found:\n"
            f"{STRATEGY_METRICS_FILE}\n\n"
            "Run backtest.py first."
        )

    print(
        "summary.json            : FOUND"
    )

    print(
        "strategy_metrics.csv    : FOUND"
    )

    print()

    print(
        "Backtest execution      : "
        "NOT triggered"
    )

    print(
        "Fresh data download     : "
        "NOT triggered"
    )

    print()


# =============================================================================
# LOAD SUMMARY
# =============================================================================

def load_summary() -> dict:

    try:

        with SUMMARY_FILE.open(
            "r",
            encoding="utf-8",
        ) as file:

            payload = json.load(file)

    except Exception as exc:

        raise RuntimeError(
            "Unable to read summary.json:\n"
            f"{exc}"
        ) from exc

    if not isinstance(
        payload,
        dict,
    ):

        raise RuntimeError(
            "summary.json does not contain "
            "a JSON object."
        )

    return payload


# =============================================================================
# LAST BACKTEST INFORMATION
# =============================================================================

def get_last_backtest_datetime(
    summary: dict,
) -> tuple[
    datetime | None,
    str,
]:

    # Try common timestamp fields first.

    possible_fields = [
        "run_timestamp",
        "generated_at",
        "created_at",
        "timestamp",
        "run_datetime",
        "backtest_run_time",
        "last_run",
    ]

    for field in possible_fields:

        value = summary.get(
            field
        )

        if not value:

            continue

        text = str(value).strip()

        try:

            parsed = datetime.fromisoformat(
                text.replace(
                    "Z",
                    "+00:00",
                )
            )

            if parsed.tzinfo is not None:

                parsed = parsed.replace(
                    tzinfo=None
                )

            return (
                parsed,
                f"summary.json -> {field}",
            )

        except ValueError:

            continue

    # Fallback:
    #
    # If backtest.py did not save a run timestamp,
    # use summary.json modification time.
    #
    # This does NOT run anything.

    modified = get_file_modified_time(
        SUMMARY_FILE
    )

    return (
        modified,
        "summary.json file modification time",
    )


# =============================================================================
# RESEARCH FRESHNESS
# =============================================================================

def check_research_freshness(
    summary: dict,
) -> tuple[
    datetime | None,
    bool,
]:

    last_run, source = (
        get_last_backtest_datetime(
            summary
        )
    )

    print("=" * 100)
    print("RESEARCH FRESHNESS")
    print("=" * 100)

    print()

    print(
        f"Last backtest run       : "
        f"{format_datetime(last_run)}"
    )

    print(
        f"Timestamp source        : "
        f"{source}"
    )

    age = days_since(
        last_run
    )

    if age is None:

        print(
            "Research age            : "
            "UNKNOWN"
        )

        print()

        print(
            "WARNING: Unable to determine "
            "research age."
        )

        print(
            "main.py will not run a backtest."
        )

        print()

        return (
            last_run,
            False,
        )

    print(
        f"Research age            : "
        f"{age:.1f} days"
    )

    print(
        f"Maximum allowed age     : "
        f"{MAX_RESULT_AGE_DAYS} days"
    )

    print()

    if age > MAX_RESULT_AGE_DAYS:

        print(
            "STATUS                  : "
            "STALE RESULTS"
        )

        print()

        print(
            "No new backtest will be run automatically."
        )

        print(
            "Run backtest.py manually to refresh research."
        )

        print()

        return (
            last_run,
            False,
        )

    print(
        "STATUS                  : "
        "FRESH ENOUGH FOR PRODUCTION READ"
    )

    print()

    return (
        last_run,
        True,
    )


# =============================================================================
# CONFIGURATION FROM SAVED RESULTS
# =============================================================================

def print_saved_research_configuration(
    summary: dict,
) -> None:

    print("=" * 100)
    print("SAVED RESEARCH CONFIGURATION")
    print("=" * 100)

    print()

    print(
        f"Backtest start          : "
        f"{summary.get('backtest_start', 'N/A')}"
    )

    print(
        f"Backtest end            : "
        f"{summary.get('backtest_end', 'N/A')}"
    )

    print(
        f"Monthly SIP used        : "
        f"{format_money(summary.get('monthly_sip'))}"
    )

    print(
        f"Historical portfolio    : "
        f"{summary.get('portfolio_size', 'Rank #1')}"
    )

    print(
        "Historical allocation   : "
        "100% to Rank #1"
    )

    print(
        "Displayed ranks         : "
        f"Top {DISPLAY_RANKS}"
    )

    print()

    print(
        "IMPORTANT:"
    )

    print(
        "  These values are READ from saved research."
    )

    print(
        "  main.py does not recalculate historical metrics."
    )

    print()


# =============================================================================
# STRATEGY SELECTION
# =============================================================================

def select_live_strategy(
    summary: dict,
) -> tuple[
    str | None,
    str | None,
    str | None,
]:

    highest_xirr = summary.get(
        "strongest_return_strategy"
    )

    highest_risk_adjusted = summary.get(
        "strongest_risk_adjusted_strategy"
    )

    if (
        highest_xirr
        and highest_risk_adjusted
        and
        str(highest_xirr).upper()
        ==
        str(highest_risk_adjusted).upper()
    ):

        strategy = str(
            highest_xirr
        ).upper()

        return (
            strategy,
            strategy,
            strategy,
        )

    return (
        None,
        (
            str(highest_xirr).upper()
            if highest_xirr
            else None
        ),
        (
            str(highest_risk_adjusted).upper()
            if highest_risk_adjusted
            else None
        ),
    )


# =============================================================================
# STRATEGY SELECTION DETAILS
# =============================================================================

def print_strategy_selection(
    live_strategy: str | None,
    summary: dict,
) -> None:

    print("=" * 100)
    print("STRATEGY SELECTION")
    print("=" * 100)

    print()

    highest_xirr = summary.get(
        "strongest_return_strategy"
    )

    highest_risk_adjusted = summary.get(
        "strongest_risk_adjusted_strategy"
    )

    print(
        f"Highest historical XIRR : "
        f"{highest_xirr}"
    )

    print(
        f"Highest risk-adjusted   : "
        f"{highest_risk_adjusted}"
    )

    print()

    if live_strategy is None:

        print(
            "LIVE STRATEGY STATUS    : "
            "NOT ACTIVATED"
        )

        print()

        print(
            "Reason:"
        )

        print(
            "  The highest-XIRR and highest-risk-adjusted "
            "strategies disagree."
        )

        print(
            "  main.py will not silently choose between them."
        )

        print()

        return

    print(
        f"SELECTED STRATEGY       : "
        f"{live_strategy}"
    )

    print()

    print(
        "Selection rule:"
    )

    print(
        "  1. Identify highest historical XIRR."
    )

    print(
        "  2. Identify highest risk-adjusted composite."
    )

    print(
        "  3. Require both to identify the same strategy."
    )

    print(
        "  4. Only then activate that strategy for the "
        "current Top-1 SIP ranking."
    )

    print()

    print(
        "This is a rule-based selection from the saved "
        "backtest evidence."
    )

    print(
        "It is not a forecast of future performance."
    )

    print()


# =============================================================================
# STRATEGY-SPECIFIC METHODOLOGY
# =============================================================================

def print_strategy_methodology(
    strategy: str | None,
) -> None:

    print("=" * 100)
    print("SELECTED STRATEGY METHODOLOGY")
    print("=" * 100)

    print()

    if strategy is None:

        print(
            "No strategy activated."
        )

        print()

        return

    if strategy == "TREND":

        print(
            "TREND"
        )

        print(
            "  Purpose:"
        )

        print(
            "    Identify funds showing sustained price momentum "
            "and improving trend characteristics."
        )

        print()

        print(
            "  Scoring components:"
        )

        print(
            "    30% : 12-month momentum"
        )

        print(
            "    15% : 24-month momentum"
        )

        print(
            "    35% : Trend score"
        )

        print(
            "    20% : Momentum acceleration"
        )

        print()

        print(
            "  Interpretation:"
        )

        print(
            "    The strategy gives substantial importance to "
            "persistent trend strength rather than relying "
            "only on the latest return."
        )

        print()

        print(
            "  Drawdown:"
        )

        print(
            "    Drawdown is NOT a TREND scoring component."
        )

        print(
            "    It is displayed separately as a risk diagnostic."
        )

    elif strategy == "MOMENTUM":

        print(
            "MOMENTUM"
        )

        print(
            "  Scoring components:"
        )

        print(
            "    50% : 12-month momentum"
        )

        print(
            "    25% : 24-month momentum"
        )

        print(
            "    25% : 36-month momentum"
        )

        print()

        print(
            "  Purpose:"
        )

        print(
            "    Rank funds primarily by multi-period momentum."
        )

    elif strategy == "DRAWDOWN_RECOVERY":

        print(
            "DRAWDOWN_RECOVERY"
        )

        print(
            "  Scoring components:"
        )

        print(
            "    20% : 12-month momentum"
        )

        print(
            "    20% : Trend"
        )

        print(
            "    20% : Drawdown"
        )

        print(
            "    15% : Distance from historical high"
        )

        print(
            "    25% : Recovery score"
        )

        print()

        print(
            "  Purpose:"
        )

        print(
            "    Combine recovery characteristics with momentum "
            "and trend information."
        )

    elif strategy == "QUALITY_MOMENTUM":

        print(
            "QUALITY_MOMENTUM"
        )

        print(
            "  Purpose:"
        )

        print(
            "    Combine the strategy's quality-related measures "
            "with momentum characteristics."
        )

        print()

        print(
            "  Exact weights:"
        )

        print(
            "    Defined by the historical engine in backtest.py."
        )

    elif strategy == "RISK_ADJUSTED":

        print(
            "RISK_ADJUSTED"
        )

        print(
            "  Purpose:"
        )

        print(
            "    Emphasize return characteristics while accounting "
            "for risk and drawdown-related behaviour."
        )

        print()

        print(
            "  Exact weights:"
        )

        print(
            "    Defined by the historical engine in backtest.py."
        )

    elif strategy == "CONSISTENCY":

        print(
            "CONSISTENCY"
        )

        print(
            "  Purpose:"
        )

        print(
            "    Prefer funds demonstrating more persistent "
            "performance characteristics."
        )

        print()

        print(
            "  Exact weights:"
        )

        print(
            "    Defined by the historical engine in backtest.py."
        )

    else:

        print(
            f"Strategy: {strategy}"
        )

        print(
            "Detailed methodology is defined in backtest.py."
        )

    print()


# =============================================================================
# HISTORICAL EVIDENCE
# =============================================================================

def print_historical_evidence(
    live_strategy: str | None,
) -> None:

    print("=" * 100)
    print("HISTORICAL EVIDENCE")
    print("=" * 100)

    print()

    try:

        import pandas as pd

        df = pd.read_csv(
            STRATEGY_METRICS_FILE
        )

    except Exception as exc:

        raise RuntimeError(
            "Unable to read strategy_metrics.csv:\n"
            f"{exc}"
        ) from exc

    if df.empty:

        raise RuntimeError(
            "strategy_metrics.csv is empty."
        )

    if "strategy" not in df.columns:

        raise RuntimeError(
            "strategy_metrics.csv does not contain "
            "a 'strategy' column."
        )

    print(
        f"{'Strategy':<22}"
        f"{'XIRR':>9}"
        f"{'TWR':>10}"
        f"{'Vol':>9}"
        f"{'MaxDD':>10}"
        f"{'Sharpe':>9}"
        f"{'Sortino':>9}"
        f"{'Calmar':>9}"
        f"{'Risk':>9}"
        f"{'Final Value':>16}"
    )

    print("-" * 125)

    for _, row in df.iterrows():

        strategy = str(
            row.get(
                "strategy",
                "",
            )
        )

        print(
            f"{strategy:<22}"
            f"{format_pct(row.get('xirr')):>9}"
            f"{format_pct(row.get('twr_return')):>10}"
            f"{format_pct(row.get('volatility')):>9}"
            f"{format_pct(row.get('max_drawdown')):>10}"
            f"{format_number(row.get('sharpe')):>9}"
            f"{format_number(row.get('sortino')):>9}"
            f"{format_number(row.get('calmar')):>9}"
            f"{format_number(row.get('risk_adjusted_composite'), 2):>9}"
            f"{format_money(row.get('final_value')):>16}"
        )

    print()

    if live_strategy is None:

        return

    matches = df[
        df["strategy"]
        .astype(str)
        .str.upper()
        ==
        live_strategy.upper()
    ]

    if matches.empty:

        print(
            f"No detailed evidence row found for "
            f"{live_strategy}."
        )

        print()

        return

    row = matches.iloc[0]

    print(
        f"SELECTED STRATEGY EVIDENCE : "
        f"{live_strategy}"
    )

    print()

    print(
        f"  Historical XIRR          : "
        f"{format_pct(row.get('xirr'))}"
    )

    print(
        f"  TWR return               : "
        f"{format_pct(row.get('twr_return'))}"
    )

    print(
        f"  Volatility               : "
        f"{format_pct(row.get('volatility'))}"
    )

    print(
        f"  Maximum drawdown         : "
        f"{format_pct(row.get('max_drawdown'))}"
    )

    print(
        f"  Sharpe                   : "
        f"{format_number(row.get('sharpe'))}"
    )

    print(
        f"  Sortino                  : "
        f"{format_number(row.get('sortino'))}"
    )

    print(
        f"  Calmar                   : "
        f"{format_number(row.get('calmar'))}"
    )

    print(
        f"  Risk-adjusted composite  : "
        f"{format_number(row.get('risk_adjusted_composite'), 2)}"
    )

    print(
        f"  Contributions            : "
        f"{format_money(row.get('contributions'))}"
    )

    print(
        f"  SIP count                : "
        f"{safe_int(row.get('sip_count')) or 'N/A'}"
    )

    print(
        f"  Final value              : "
        f"{format_money(row.get('final_value'))}"
    )

    print()

    print(
        "Evidence says:"
    )

    print(
        "  TREND was identified by the saved backtest as both "
        "the highest-XIRR strategy and highest risk-adjusted "
        "composite."
        if live_strategy == "TREND"
        else
        "The selected strategy was identified by both saved "
        "selection criteria."
    )

    print()

    print(
        "Important:"
    )

    print(
        "  Historical evidence describes what happened in "
        "the tested period."
    )

    print(
        "  It does not guarantee future returns."
    )

    print()


# =============================================================================
# CURRENT MARKET
# =============================================================================

def print_current_market(
    summary: dict,
) -> None:

    print("=" * 100)
    print("CURRENT MARKET")
    print("=" * 100)

    print()

    market = summary.get(
        "market",
        {},
    )

    if not isinstance(
        market,
        dict,
    ):

        market = {}

    print(
        f"Latest completed month     : "
        f"{market.get('latest_completed_month', 'N/A')}"
    )

    print(
        f"Regime                    : "
        f"{market.get('regime', 'N/A')}"
    )

    print(
        f"Above 12M MA breadth      : "
        f"{format_pct(market.get('breadth'))}"
    )

    print(
        f"Positive 12M momentum     : "
        f"{format_pct(market.get('positive_momentum'))}"
    )

    print(
        f"Median 12M momentum       : "
        f"{format_pct(market.get('median_momentum'))}"
    )

    print(
        f"Median trend              : "
        f"{format_pct(market.get('median_trend'))}"
    )

    print()

    print(
        "These figures describe the latest saved market "
        "snapshot from the backtest run."
    )

    print()


# =============================================================================
# CURRENT TOP 5
# =============================================================================

def load_current_top5(
    strategy: str,
):

    filename = (
        RESULTS_DIR
        /
        f"current_top5_{strategy.lower()}.csv"
    )

    if not filename.exists():

        return None, filename

    try:

        import pandas as pd

        df = pd.read_csv(
            filename
        )

    except Exception as exc:

        raise RuntimeError(
            f"Unable to read {filename.name}:\n"
            f"{exc}"
        ) from exc

    if df.empty:

        return None, filename

    if "rank" in df.columns:

        df = df.sort_values(
            "rank"
        )

    return (
        df.reset_index(
            drop=True
        ),
        filename,
    )


# =============================================================================
# CURRENT TOP 5 DISPLAY
# =============================================================================

def print_current_top5(
    df,
    strategy: str,
) -> None:

    print("=" * 100)
    print(
        f"CURRENT TOP {DISPLAY_RANKS} - "
        f"{strategy}"
    )
    print("=" * 100)

    print()

    if df is None or df.empty:

        print(
            "Current Top 5 data unavailable."
        )

        print()

        return

    for _, row in df.head(
        DISPLAY_RANKS
    ).iterrows():

        rank = safe_int(
            row.get("rank")
        )

        name = row.get(
            "name",
            "N/A",
        )

        print(
            f"{rank if rank is not None else '?':>2}. "
            f"{name}"
        )

        print(
            f"    Score          : "
            f"{format_number(row.get('strategy_score'), 4)}"
        )

        print(
            f"    12M return     : "
            f"{format_pct(row.get('ret_12'))}"
        )

        print(
            f"    36M return     : "
            f"{format_pct(row.get('ret_36'))}"
        )

        print(
            f"    Trend          : "
            f"{format_pct(row.get('trend_ratio'))}"
        )

        print(
            f"    Historical DD  : "
            f"{format_pct(row.get('max_drawdown'))}"
        )

        print()


# =============================================================================
# CURRENT TOP-1 SIP ACTION
# =============================================================================

def print_current_top1_action(
    df,
    strategy: str,
    summary: dict,
) -> None:

    print("=" * 100)
    print("CURRENT MONTHLY SIP ACTION")
    print("=" * 100)

    print()

    if df is None or df.empty:

        print(
            "NO SIP ACTION."
        )

        print(
            "Current Rank #1 is unavailable."
        )

        print()

        return

    row = df.iloc[0]

    rank = safe_int(
        row.get("rank")
    )

    name = row.get(
        "name",
        "N/A",
    )

    code = row.get(
        "code",
        "N/A",
    )

    score = row.get(
        "strategy_score"
    )

    current_nav = row.get(
        "current_nav"
    )

    ret_12 = row.get(
        "ret_12"
    )

    ret_36 = row.get(
        "ret_36"
    )

    trend_ratio = row.get(
        "trend_ratio"
    )

    max_drawdown = row.get(
        "max_drawdown"
    )

    market = summary.get(
        "market",
        {},
    )

    if not isinstance(
        market,
        dict,
    ):

        market = {}

    latest_month = market.get(
        "latest_completed_month",
        summary.get(
            "backtest_end",
            "N/A",
        ),
    )

    print(
        f"Strategy                  : "
        f"{strategy}"
    )

    print(
        f"Data used through         : "
        f"{latest_month}"
    )

    print(
        f"Monthly SIP               : "
        f"{format_money(LIVE_SIP_AMOUNT)}"
    )

    print(
        "NEW SIP allocation        : "
        "100% to Rank #1"
    )

    print(
        f"Informational ranks       : "
        f"#2 to #{DISPLAY_RANKS}"
    )

    print(
        "Existing holdings         : "
        "Remain invested"
    )

    print(
        "Automatic selling         : "
        "NO"
    )

    print(
        "Automatic rebalancing    : "
        "NO"
    )

    print()

    print("-" * 100)

    print()

    print(
        "CURRENT RANK #1"
    )

    print()

    print(
        f"Fund                      : "
        f"{name}"
    )

    print(
        f"Scheme code               : "
        f"{code}"
    )

    print(
        f"Rank                      : "
        f"#{rank if rank is not None else 1}"
    )

    print(
        f"Strategy score            : "
        f"{format_number(score, 4)}"
    )

    print(
        f"Current NAV               : "
        f"{format_nav(current_nav)}"
    )

    print(
        f"12-month return           : "
        f"{format_pct(ret_12)}"
    )

    print(
        f"36-month return           : "
        f"{format_pct(ret_36)}"
    )

    print(
        f"Trend                     : "
        f"{format_pct(trend_ratio)}"
    )

    print(
        f"Historical max drawdown   : "
        f"{format_pct(max_drawdown)}"
    )

    print()

    print("=" * 100)
    print("SIP INSTRUCTION")
    print("=" * 100)

    print()

    print(
        f"{format_money(LIVE_SIP_AMOUNT)}"
        f"  ->  {name}"
    )

    print()

    print(
        "Meaning:"
    )

    print(
        "  The next ₹10,000 of NEW SIP money goes "
        "to the current Rank #1."
    )

    print(
        "  The previous month's fund is NOT sold merely "
        "because it is no longer Rank #1."
    )

    print(
        "  If Rank #1 changes next month, the NEW ₹10,000 "
        "goes to the new Rank #1."
    )

    print(
        "  Therefore, over time, the portfolio can contain "
        "multiple funds from different months."
    )

    print()


# =============================================================================
# DRAWDOWN EXPLANATION
# =============================================================================

def print_drawdown_explanation() -> None:

    print("=" * 100)
    print("WHY DRAWDOWN IS SHOWN")
    print("=" * 100)

    print()

    print(
        "Drawdown is included as a RISK DIAGNOSTIC."
    )

    print()

    print(
        "It answers:"
    )

    print(
        "  How far did the fund historically fall from a "
        "previous high during the measured period?"
    )

    print()

    print(
        "Example from the latest Top 5:"
    )

    print(
        "  Rank #1 BANK OF INDIA SMALL CAP FUND:"
    )

    print(
        "    Historical max DD = -24.75%"
    )

    print()

    print(
        "  This means the historical maximum decline from a "
        "previous peak was approximately 24.75%."
    )

    print()

    print(
        "IMPORTANT:"
    )

    print(
        "  Drawdown is NOT a prediction that the fund will "
        "fall by that amount in the future."
    )

    print()

    print(
        "For TREND specifically:"
    )

    print(
        "  Drawdown does NOT form part of the TREND score."
    )

    print(
        "  It is shown so the return/trend selection can be "
        "viewed together with historical downside behaviour."
    )

    print()


# =============================================================================
# HISTORICAL SIP MECHANICS
# =============================================================================

def print_sip_mechanics() -> None:

    print("=" * 100)
    print("HOW THE TOP-1 SIP WORKS")
    print("=" * 100)

    print()

    print(
        "Each month:"
    )

    print(
        "  1. Calculate the strategy ranking."
    )

    print(
        "  2. Rank the eligible funds."
    )

    print(
        "  3. Take Rank #1."
    )

    print(
        "  4. Invest the NEW ₹10,000 into Rank #1."
    )

    print(
        "  5. Keep all previous holdings."
    )

    print()

    print(
        "Therefore:"
    )

    print(
        "  Rank #1 can change from month to month."
    )

    print(
        "  The SIP can therefore go into a NEW fund "
        "in a later month."
    )

    print(
        "  There is NO requirement that Rank #1 remain "
        "the same fund."
    )

    print()

    print(
        "But:"
    )

    print(
        "  A Rank #1 change does NOT trigger a sale "
        "of the previous fund."
    )

    print()


# =============================================================================
# BACKTEST OBSERVATIONS
# =============================================================================

def print_backtest_observations(
    summary: dict,
) -> None:

    print("=" * 100)
    print("LATEST BACKTEST OBSERVATIONS")
    print("=" * 100)

    print()

    print(
        "Backtest period:"
    )

    print(
        f"  {summary.get('backtest_start', 'N/A')}"
        f" -> "
        f"{summary.get('backtest_end', 'N/A')}"
    )

    print()

    print(
        "Latest supplied run:"
    )

    print(
        "  42 Direct-Growth Small Cap schemes verified."
    )

    print(
        "  42 NAV datasets downloaded."
    )

    print(
        "  27 funds had at least 36 months of history."
    )

    print(
        "  Historical decision dates: "
        "2017-01-31 -> 2026-09-30."
    )

    print(
        "  Completed SIPs per strategy: 116."
    )

    print(
        "  Contributions per strategy: ₹11,60,000."
    )

    print(
        "  One decision month was skipped because no ranked "
        "candidate had a usable post-decision NAV."
    )

    print()

    print(
        "Latest market snapshot:"
    )

    print(
        "  Regime: BULL."
    )

    print(
        "  Above 12M MA breadth: 100%."
    )

    print(
        "  Positive 12M momentum: 92.59%."
    )

    print(
        "  Median 12M momentum: 10.97%."
    )

    print(
        "  Median trend: 8.42%."
    )

    print()

    print(
        "These are observations from the saved backtest."
    )

    print(
        "main.py does not recompute them."
    )

    print()


# =============================================================================
# METHODOLOGY
# =============================================================================

def print_methodology(
    summary: dict,
) -> None:

    print("=" * 100)
    print("METHODOLOGY AND DATA")
    print("=" * 100)

    print()

    print(
        "Universe:"
    )

    print(
        "  Current Direct-Growth Small Cap mutual-fund "
        "universe from MFAPI."
    )

    print(
        "  The universe is dynamic when backtest.py is run."
    )

    print(
        "  main.py does NOT refresh the universe."
    )

    print()

    print(
        "Historical data:"
    )

    print(
        f"  Backtest period: "
        f"{summary.get('backtest_start', 'N/A')}"
        f" -> "
        f"{summary.get('backtest_end', 'N/A')}"
    )

    print()

    print(
        "Current ranking data:"
    )

    print(
        f"  Latest completed month: "
        f"{summary.get('market', {}).get('latest_completed_month', 'N/A')}"
    )

    print()

    print(
        "Decision frequency:"
    )

    print(
        "  Monthly at completed month-end."
    )

    print()

    print(
        "Historical purchase logic:"
    )

    print(
        "  First usable NAV strictly after the decision date."
    )

    print(
        "  If a ranked candidate has no usable post-decision "
        "NAV, the engine can move to the next-ranked candidate."
    )

    print()

    print(
        "Minimum historical history:"
    )

    print(
        "  36 months."
    )

    print()

    print(
        "Production SIP:"
    )

    print(
        "  ₹10,000 monthly."
    )

    print(
        "  100% to Rank #1."
    )

    print(
        "  #2-#5 informational only."
    )

    print(
        "  Previous holdings remain invested."
    )

    print()


# =============================================================================
# LIMITATIONS
# =============================================================================

def print_limitations() -> None:

    print("=" * 100)
    print("IMPORTANT RESEARCH LIMITATIONS")
    print("=" * 100)

    print()

    print(
        "1. Historical backtest performance is not a forecast."
    )

    print(
        "2. The current-universe methodology introduces "
        "survivorship bias into historical results."
    )

    print(
        "3. Historical results depend on the tested period "
        "and methodology."
    )

    print(
        "4. Mutual-fund NAV execution may differ from a "
        "simple theoretical backtest purchase date."
    )

    print(
        "5. One month was skipped in the supplied run because "
        "no ranked candidate had a usable post-decision NAV."
    )

    print(
        "6. Candidate NAV failures do not necessarily mean "
        "a SIP was skipped because replacement candidates "
        "can be considered."
    )

    print(
        "7. Drawdown is historical downside information, "
        "not a future-loss prediction."
    )

    print(
        "8. Top-1 means the allocation of NEW SIP money. "
        "It does not mean selling the entire accumulated portfolio."
    )

    print()


# =============================================================================
# RESULT FILES
# =============================================================================

def print_result_files() -> None:

    print("=" * 100)
    print("SAVED RESULT FILES")
    print("=" * 100)

    print()

    if not RESULTS_DIR.exists():

        print(
            "Results directory not found."
        )

        print()

        return

    files = sorted(
        file
        for file in RESULTS_DIR.iterdir()
        if file.is_file()
    )

    if not files:

        print(
            "No files found."
        )

        print()

        return

    for file in files:

        try:

            size_kb = (
                file.stat().st_size
                / 1024
            )

            modified = get_file_modified_time(
                file
            )

            print(
                f"{file.name:<60}"
                f"{size_kb:>10.1f} KB"
                f"  {format_datetime(modified)}"
            )

        except OSError:

            print(
                file.name
            )

    print()


# =============================================================================
# FINAL STATUS
# =============================================================================

def print_final_status(
    live_strategy: str | None,
    results_dir: Path,
    elapsed: float,
    research_fresh: bool,
    sip_action_available: bool,
) -> None:

    print("=" * 100)
    print("SMALLCAPSIPLAB COMPLETE")
    print("=" * 100)

    print()

    print(
        "Execution mode            : "
        "READ SAVED RESULTS ONLY"
    )

    print(
        "Backtest executed         : "
        "NO"
    )

    print(
        "MFAPI downloaded           : "
        "NO"
    )

    print(
        "NAV history downloaded     : "
        "NO"
    )

    print()

    print(
        f"Research freshness         : "
        f"{'OK' if research_fresh else 'STALE/UNKNOWN'}"
    )

    print(
        f"Selected strategy          : "
        f"{live_strategy or 'NONE'}"
    )

    print(
        f"Monthly SIP                : "
        f"{format_money(LIVE_SIP_AMOUNT)}"
    )

    print(
        "New SIP allocation         : "
        "100% to Rank #1"
    )

    print(
        f"Informational ranks        : "
        f"Top {DISPLAY_RANKS}"
    )

    print(
        f"SIP action available       : "
        f"{'YES' if sip_action_available else 'NO'}"
    )

    print()

    print(
        "Results directory:"
    )

    print(
        f"  {results_dir}"
    )

    print()

    print(
        f"main.py runtime            : "
        f"{elapsed:.2f} seconds"
    )

    print()

    print(
        "IMPORTANT:"
    )

    print(
        "  This runtime excludes the historical backtest "
        "and data-download process because main.py does "
        "not execute them."
    )

    print()


# =============================================================================
# MAIN
# =============================================================================

def main() -> int:

    start_time = time.perf_counter()

    live_strategy: str | None = None

    research_fresh = False

    sip_action_available = False

    try:

        # =====================================================================
        # HEADER
        # =====================================================================

        print_header()

        # =====================================================================
        # VALIDATE EXISTING RESULTS
        # =====================================================================

        validate_result_files()

        # =====================================================================
        # LOAD SAVED SUMMARY
        # =====================================================================

        summary = load_summary()

        # =====================================================================
        # CHECK RESEARCH FRESHNESS
        # =====================================================================

        (
            last_backtest_run,
            research_fresh,
        ) = check_research_freshness(
            summary
        )

        # =====================================================================
        # SAVED RESEARCH CONFIGURATION
        # =====================================================================

        print_saved_research_configuration(
            summary
        )

        # =====================================================================
        # SELECT STRATEGY FROM SAVED RESULTS
        # =====================================================================

        (
            live_strategy,
            highest_xirr_strategy,
            highest_risk_strategy,
        ) = select_live_strategy(
            summary
        )

        print_strategy_selection(
            live_strategy,
            summary,
        )

        # =====================================================================
        # STRATEGY METHODOLOGY
        # =====================================================================

        print_strategy_methodology(
            live_strategy
        )

        # =====================================================================
        # HISTORICAL EVIDENCE
        # =====================================================================

        print_historical_evidence(
            live_strategy
        )

        # =====================================================================
        # CURRENT MARKET
        # =====================================================================

        print_current_market(
            summary
        )

        # =====================================================================
        # CURRENT TOP 5
        # =====================================================================

        current_top5 = None

        current_top5_file = None

        if live_strategy is not None:

            (
                current_top5,
                current_top5_file,
            ) = load_current_top5(
                live_strategy
            )

            if current_top5 is None:

                print()

                print(
                    "=" * 100
                )

                print(
                    "CURRENT TOP 5"
                )

                print(
                    "=" * 100
                )

                print()

                print(
                    "Current Top 5 file not found:"
                )

                print(
                    f"  {current_top5_file}"
                )

                print()

            else:

                print_current_top5(
                    current_top5,
                    live_strategy,
                )

        # =====================================================================
        # SIP ACTION
        # =====================================================================

        if (
            live_strategy is not None
            and
            research_fresh
            and
            current_top5 is not None
            and
            not current_top5.empty
        ):

            print_current_top1_action(
                current_top5,
                live_strategy,
                summary,
            )

            sip_action_available = True

        else:

            print()

            print(
                "=" * 100
            )

            print(
                "CURRENT MONTHLY SIP ACTION"
            )

            print(
                "=" * 100
            )

            print()

            print(
                "NO SIP ACTION ISSUED."
            )

            print()

            if not research_fresh:

                print(
                    "Reason: saved research is stale or "
                    "its age could not be verified."
                )

                print(
                    "Run backtest.py manually to refresh it."
                )

            elif live_strategy is None:

                print(
                    "Reason: highest-XIRR and highest-risk-adjusted "
                    "strategies disagree."
                )

            elif current_top5 is None:

                print(
                    "Reason: current Top 5 result file is missing."
                )

            print()

            print(
                "main.py will NOT run backtest.py automatically."
            )

            print()

        # =====================================================================
        # DRAWdown
        # =====================================================================

        print_drawdown_explanation()

        # =====================================================================
        # SIP MECHANICS
        # =====================================================================

        print_sip_mechanics()

        # =====================================================================
        # BACKTEST OBSERVATIONS
        # =====================================================================

        print_backtest_observations(
            summary
        )

        # =====================================================================
        # METHODOLOGY
        # =====================================================================

        print_methodology(
            summary
        )

        # =====================================================================
        # LIMITATIONS
        # =====================================================================

        print_limitations()

        # =====================================================================
        # RESULT FILES
        # =====================================================================

        print_result_files()

        # =====================================================================
        # FINAL STATUS
        # =====================================================================

        elapsed = (
            time.perf_counter()
            - start_time
        )

        print_final_status(
            live_strategy,
            RESULTS_DIR,
            elapsed,
            research_fresh,
            sip_action_available,
        )

        return 0

    except KeyboardInterrupt:

        elapsed = (
            time.perf_counter()
            - start_time
        )

        print()

        print("=" * 100)
        print("SMALLCAPSIPLAB - INTERRUPTED")
        print("=" * 100)

        print()

        print(
            f"Runtime before interruption : "
            f"{elapsed:.2f} seconds"
        )

        print()

        return 130

    except Exception as exc:

        elapsed = (
            time.perf_counter()
            - start_time
        )

        print()

        print("=" * 100)
        print("SMALLCAPSIPLAB - FAILED")
        print("=" * 100)

        print()

        print(
            f"Error                      : "
            f"{exc}"
        )

        print()

        print(
            f"Runtime before failure     : "
            f"{elapsed:.2f} seconds"
        )

        print()

        raise


# =============================================================================
# SCRIPT ENTRY
# =============================================================================

if __name__ == "__main__":

    raise SystemExit(
        main()
    )